#!/usr/bin/env bash
# auto-archive-hook.sh
#
# Purpose : Claude Code Stop hook — appends a timestamped turn marker to a
#           daily rolling session log in methodology/chat-history/.
#           Runs automatically after every Claude response when archiving is on.
# Inputs  : JSON context on stdin (from Claude Code hook harness):
#             { "session_id": "...", "transcript_path": "...", ... }
# Outputs : methodology/chat-history/YYYY-MM-DD_auto.md (appended or created)
# Deps    : bash 3+, date — no external packages

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ARCHIVE_DIR="$SCRIPT_DIR/../methodology/chat-history"
mkdir -p "$ARCHIVE_DIR"

TODAY="$(date +%Y-%m-%d)"
NOW="$(date +%H:%M:%S)"
SESSION_FILE="$ARCHIVE_DIR/${TODAY}_auto.md"

# Parse session_id and transcript_path out of stdin JSON if available
SESSION_ID=""
TRANSCRIPT_PATH=""
if read -t 0.1 -r RAW_JSON 2>/dev/null; then
  SESSION_ID="$(echo "$RAW_JSON"   | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('session_id',''))" 2>/dev/null || true)"
  TRANSCRIPT_PATH="$(echo "$RAW_JSON" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('transcript_path',''))" 2>/dev/null || true)"
fi

# Create file with YAML front matter if this is the first turn today
if [[ ! -f "$SESSION_FILE" ]]; then
  {
    echo "---"
    echo "date: $TODAY"
    echo "mode: auto-session-log"
    [[ -n "$SESSION_ID" ]] && echo "session_id: $SESSION_ID"
    echo "---"
    echo ""
    echo "# Auto session log — $TODAY"
    echo ""
    echo "_Generated by auto-archive-hook. Fill in content after each turn._"
    echo ""
    [[ -n "$TRANSCRIPT_PATH" ]] && echo "_Transcript: \`$TRANSCRIPT_PATH\`_" && echo ""
  } > "$SESSION_FILE"
fi

# Append a turn separator with timestamp
{
  echo "---"
  echo ""
  echo "### Turn — $NOW"
  echo ""
  echo "<!-- Summarise this turn: what was asked, what was done, any decisions -->"
  echo ""
} >> "$SESSION_FILE"

# Emit path so it shows up in Claude Code output
echo "Archived turn → $SESSION_FILE"
